const pool = require("../../database/pool");
const Joi = require("joi");

//Book id need to be autogenerated
//Books model
const bookSchema = Joi.object({
  id: Joi.string().required(),
  name: Joi.string().required().alphanum().max(64),
  author: Joi.string().required().max(64),
  price: Joi.number().required(),
  publisher: Joi.string().required().max(64),
  category: Joi.string().required().max(24),
});

async function addBook(req, res) {
  try {
    const { error } = bookSchema.validate(req.body);
    if (error) {
      return res.status(400).json({ status: false, msg: error.message });
    }

    const { id, name, author, price, publisher, category } = req.body;

    // Check if book already exists
    const exists = await pool.query("SELECT * FROM books WHERE id = $1", [id]);
    if (exists.rowCount !== 0) {
      return res
        .status(400)
        .json({ status: false, msg: "Book already exists" });
    }

    // Insert the book into the database
    await pool.query(
      "INSERT INTO books (id, name, author, price, publisher, category, available) VALUES ($1, $2, $3, $4, $5, $6, $7)",
      [id, name, author, price, publisher, category, true]
    );
    console.log("Book added " + id);
    res.status(200).json({ status: true, msg: "Book added" });
  } catch (error) {
    console.error("Error adding book:", error);
    res.status(500).json({ status: false, msg: "Something went wrong" });
  }
}

module.exports = addBook;
