const pool = require("../../database/pool");
const Joi = require("joi");

//Book id need to be autogenerated
//Books model
const bookSchema = Joi.object({
  name: Joi.string().required().alphanum().max(64),
  author: Joi.string().required().max(64),
  price: Joi.number().required(),
  publisher: Joi.string().required().max(64),
  category: Joi.string().required().max(24),
});

async function addBook(req, res) {
  try {
    const { error } = bookSchema.validate(req.body);
    if (error) {
      return res.status(400).json({ status: false, msg: error.message });
    }

    const { name, author, price, publisher, category } = req.body;

    const num = (
      await pool.query("select unique_count from BOOK_CAT where id = $1", [
        category,
      ])
    ).rows[0].unique_count;

    const newId = category + ("000" + num).slice(-3);
    await pool.query(
      "INSERT INTO books (id, name, author, price, publisher, cat_id, available) VALUES ($1, $2, $3, $4, $5, $6, $7)",
      [newId, name, author, price, publisher, category, true]
    );
    console.log("Book added " + newId);
    await pool.query("update BOOK_CAT set unique_count = unique_count+1");
    res.status(200).json({ status: true, msg: "Book added" });
  } catch (error) {
    console.error("Error adding book:", error);
    res.status(500).json({ status: false, msg: "Something went wrong" });
  }
}

module.exports = addBook;
