 CREATE TABLE BOOKS
(
    ID VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(100),
    AUTHOR VARCHAR(50),
    PRICE INT,
    PUBLISHER VARCHAR(60),
    CATEGORY VARCHAR(24),
    AVAILABLE BOOLEAN
);

CREATE TABLE TEACHERS
(
    ID VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(100),
    MOBILE_NO INT,
    CLASS VARCHAR(3),
    PASSWORD VARCHAR(64)
);

CREATE TABLE STUDENTS
(
    ID VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(100),
    CLASS VARCHAR(3)
);

CREATE TABLE CONFIG
(
    KEY VARCHAR(20) PRIMARY KEY,
    VALUE VARCHAR(20)
);

CREATE TABLE ISSUES (
    ID SERIAL PRIMARY KEY,
    TID VARCHAR(5),
    STID VARCHAR(5),
    BID VARCHAR(5),
    RETURN_DATE VARCHAR(5),
    BORROW_DATE VARCHAR(5),
    FOREIGN KEY (TID) REFERENCES TEACHERS(ID),
    FOREIGN KEY (STID) REFERENCES STUDENTS(ID),
    FOREIGN KEY (BID) REFERENCES BOOKS(ID)
);


-- INSERT INTO CONFIG VALUES ("admin_pass","password");